apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-admin-binding
roleRef:
  kind: ClusterRole
  name: admin-cluster
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: my-admin # this is the 'admin' rbac group that we will bind to it the cluster role 'admin-cluster'
  apiGroup: rbac.authorization.k8s.io
