apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewer
rules:
- apiGroups: ["*"]
  resources: ["deployments","configmap","pods","secrets","services"]
  verbs: ["get", "watch", "list"]
